spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:exampledb;MODE=mysql;INIT=CREATE SCHEMA IF NOT EXISTS "public"
    username: root
    password:
    hikari:
      connection-timeout: 1000
      leak-detection-threshold: 6000
      maximum-pool-size: 20
      max-lifetime: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core: TRACE